name: Build SOD Viewer

on:
  push:
    branches: main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
      - name: Run PyInstaller
        run: |
          python -m PyInstaller SOD_Viewer.spec
      - uses: actions/upload-artifact@v4
        with:
          name: SOD Viewer Windows-x64
          path: 'dist/SOD Viewer.exe'
          
  build-linux:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Run PyInstaller
        run: |
          python -m PyInstaller SOD_Viewer.spec
      - uses: actions/upload-artifact@v4
        with:
          name: SOD Viewer Linux-x64
          path: 'dist/SOD Viewer'
    
  create-release:
    runs-on: ubuntu-24.04
    needs: [build-windows, build-linux]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        
      - name: Create release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"
            
      - name: Upload windows file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          overwrite: true
          file: './SOD Viewer Windows-x64/SOD Viewer.exe'
          asset_name: "SOD-Viewer-Windows-x64.exe"
          
      - name: Upload linux file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          overwrite: true
          file: './SOD Viewer Linux-x64/SOD Viewer'
          asset_name: "SOD-Viewer-Ubuntu-x64"
